### ISSUE TITLE
Properties instead of methods?

### ISSUE THREAD

**Issue by icanzilb** [marmelroy/ObjectiveKit#3]
I think in current trends dynamic properties are favorited over methods without parameters, e.g. you have `let ivars = mapViewClass.ivars()` this could be simply `mapViewClass.ivars` Just throwing the idea on the table

**Comment by marmelroy** [comment]
Thanks @icanzilb ! I like this idea. Dynamic properties would be much more Swift 3 like and it makes sense here as the work done computing the class attributes is fully encapsulated with no side effects.
